version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: svbrizgalov/foodgramm_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
      - media:/app/media
  frontend:
    image: svbrizgalov/foodgramm_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: svbrizgalov/foodgramm_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 7000:80
    volumes:
      - static:/static/
      - media:/media/
      - ../docs/:/usr/share/nginx/html/api/docs/
