# Generated by Django 3.2.15 on 2024-01-21 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Использованы запрещенные символы или особо запрещенное имя *me*', regex='^[\\w.@+-]+$')], verbose_name='Логин'),
        ),
    ]
